baseurl                  = "https://kurochi-w.github.io/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "kurochi's blog"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "home"                           # What to call the home page link
    footerText           = "Powered by Hugo. Copyright (c) 2019, [kurochi dev blog](/)"

# Metadata for Open Graph and Twitter
    description          = "kurochi dev blog"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "kurochi's blog"

[[params.mainMenu]]
    link = "/posts"
    text = "Posts"

[[params.mainMenu]]
    link = "/photos/mylife"
    text = "My life"

[[params.mainMenu]]
    link = "/photos/banya"
    text = "Banya's life"

[[params.mainMenu]]
    link = "/portfolio"
    text = "Portfolio"

[[params.mainMenu]]
    link = "/about"
    text = "Who is kurochi?"

[imaging]
    quality = 75
